In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from phik import resources, report

In [3]:
df_test = pd.read_csv('https://media.githubusercontent.com/media/nikitaLar-collab/My_projects/refs/heads/main/test.csv?token=CDZOY2EZ4RZHI6POQQ6KUALKK7PJI')

HTTPError: HTTP Error 404: Not Found

In [ ]:
df_train = pd.read_csv('https://media.githubusercontent.com/media/nikitaLar-collab/My_projects/refs/heads/main/train.csv?token=CDZOY2HKL2XIZWOMKPDSBBDKK7PK2')

In [ ]:
df = pd.concat([df_test, df_train], ignore_index=True)

In [ ]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,NaN
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,NaN
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,NaN
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Pclass       1309 non-null   int64
 2   Name         1309 non-null   object
 3   Sex          1309 non-null   object
 4   Age          1046 non-null   float64
 5   SibSp        1309 non-null   int64
 6   Parch        1309 non-null   int64
 7   Ticket       1309 non-null   object
 8   Fare         1308 non-null   float64
 9   Cabin        295 non-null    object
 10  Embarked     1307 non-null   object
 11  Survived     891 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 122.8+ KB

In [ ]:
df['Sex'] = df['Sex'].replace({'male': 1, 'female': 0})

C:\Users\Никита\AppData\Local\Temp\ipykernel_20516\765035159.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = df['Sex'].replace({'male': 1, 'female': 0})

In [ ]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q,NaN
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,S,NaN
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q,NaN
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S,NaN
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,887,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,NaN,S,0.0
1305,888,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,S,1.0
1306,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,NaN,S,0.0
1307,890,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C,1.0
1308,891,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,Q,0.0

In [ ]:
X = df[['Sex', 'Age', 'Fare', 'SibSp', 'Parch']]
y = df['Survived']

NameError: name 'df' is not defined